{% set name = "stem" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83fb19ffd4c9f82207c006051480389f80af221a7e4783000aedec4e384eb582

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - stem

about:
  home: https://stem.torproject.org/
  license: GNU (LGPLv3)
  license_file: LICENSE
  summary: Stem is a Python controller library that allows applications to interact with Tor (https://www.torproject.org/).
  description: Stem is a Python controller library for Tor. With it you can use Tor's control protocol to script against the Tor process, or build things such as Nyx. Stem's latest version is 1.6.0 (released November 5th, 2017).
  doc_url: https://stem.torproject.org/
  dev_url: https://gitweb.torproject.org/stem.git/

extra:
  recipe-maintainers:
    - SekouD
